import type { Base, Event, Soldier } from "./types"

export const soldiers: Soldier[] = [
  {
    id: "S-001",
    name: "John Smith",
    base: "Alpha Base",
    city: "Fort Worth",
    status: "Active",
    skills: ["Combat", "First Aid", "Navigation"],
    biometrics: {
      bloodFlow: 5.2,
      temperature: 37.1,
      adrenaline: 120,
      heartRate: 72,
      spO2: 98,
      respiratoryRate: 16,
      hrv: 65,
      systolic: 120,
      diastolic: 80,
      stressLevel: 3,
    },
    location: {
      lat: 32.7555,
      lng: -97.3308,
      formatted: "Fort Worth, TX",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-002",
    name: "Sarah Johnson",
    base: "Bravo Base",
    city: "San Diego",
    status: "Active",
    skills: ["Marksmanship", "Recon", "First Aid"],
    biometrics: {
      bloodFlow: 5.1,
      temperature: 36.9,
      adrenaline: 110,
      heartRate: 70,
      spO2: 99,
      respiratoryRate: 15,
      hrv: 68,
      systolic: 118,
      diastolic: 78,
      stressLevel: 2,
    },
    location: {
      lat: 32.7157,
      lng: -117.1611,
      formatted: "San Diego, CA",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-003",
    name: "Mark Davis",
    base: "Charlie Base",
    city: "Seattle",
    status: "Training",
    skills: ["Tactics", "Navigation", "Climbing"],
    biometrics: {
      bloodFlow: 5.4,
      temperature: 37.2,
      adrenaline: 130,
      heartRate: 75,
      spO2: 97,
      respiratoryRate: 17,
      hrv: 60,
      systolic: 122,
      diastolic: 82,
      stressLevel: 4,
    },
    location: {
      lat: 47.6062,
      lng: -122.3321,
      formatted: "Seattle, WA",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-004",
    name: "Emily Brown",
    base: "Alpha Base",
    city: "Fort Worth",
    status: "Resting",
    skills: ["Communications", "First Aid"],
    biometrics: {
      bloodFlow: 5.0,
      temperature: 36.8,
      adrenaline: 105,
      heartRate: 68,
      spO2: 99,
      respiratoryRate: 14,
      hrv: 72,
      systolic: 116,
      diastolic: 77,
      stressLevel: 1,
    },
    location: {
      lat: 32.7555,
      lng: -97.3308,
      formatted: "Fort Worth, TX",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-005",
    name: "Michael Wilson",
    base: "Delta Base",
    city: "Miami",
    status: "Deployed",
    skills: ["Combat", "Driving", "Navigation"],
    biometrics: {
      bloodFlow: 5.5,
      temperature: 37.4,
      adrenaline: 140,
      heartRate: 78,
      spO2: 96,
      respiratoryRate: 18,
      hrv: 58,
      systolic: 125,
      diastolic: 85,
      stressLevel: 5,
    },
    location: {
      lat: 25.7617,
      lng: -80.1918,
      formatted: "Miami, FL",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-006",
    name: "Laura Garcia",
    base: "Echo Base",
    city: "Denver",
    status: "Active",
    skills: ["Logistics", "First Aid", "Marksmanship"],
    biometrics: {
      bloodFlow: 5.3,
      temperature: 37.0,
      adrenaline: 115,
      heartRate: 73,
      spO2: 98,
      respiratoryRate: 16,
      hrv: 66,
      systolic: 121,
      diastolic: 79,
      stressLevel: 3,
    },
    location: {
      lat: 39.7392,
      lng: -104.9903,
      formatted: "Denver, CO",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-007",
    name: "Robert Lee",
    base: "Bravo Base",
    city: "San Diego",
    status: "Training",
    skills: ["Tactics", "Engineering"],
    biometrics: {
      bloodFlow: 5.2,
      temperature: 37.1,
      adrenaline: 112,
      heartRate: 71,
      spO2: 97,
      respiratoryRate: 15,
      hrv: 64,
      systolic: 119,
      diastolic: 80,
      stressLevel: 2,
    },
    location: {
      lat: 32.7157,
      lng: -117.1611,
      formatted: "San Diego, CA",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-008",
    name: "Jessica Martinez",
    base: "Charlie Base",
    city: "Seattle",
    status: "Resting",
    skills: ["Communications", "Navigation"],
    biometrics: {
      bloodFlow: 4.9,
      temperature: 36.7,
      adrenaline: 100,
      heartRate: 65,
      spO2: 99,
      respiratoryRate: 14,
      hrv: 70,
      systolic: 114,
      diastolic: 75,
      stressLevel: 1,
    },
    location: {
      lat: 47.6062,
      lng: -122.3321,
      formatted: "Seattle, WA",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-009",
    name: "David Anderson",
    base: "Echo Base",
    city: "Denver",
    status: "Active",
    skills: ["Combat", "Tactics", "Driving"],
    biometrics: {
      bloodFlow: 5.6,
      temperature: 37.3,
      adrenaline: 135,
      heartRate: 76,
      spO2: 96,
      respiratoryRate: 17,
      hrv: 62,
      systolic: 124,
      diastolic: 83,
      stressLevel: 4,
    },
    location: {
      lat: 39.7392,
      lng: -104.9903,
      formatted: "Denver, CO",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "S-010",
    name: "Karen Thompson",
    base: "Delta Base",
    city: "Miami",
    status: "Deployed",
    skills: ["Engineering", "Marksmanship"],
    biometrics: {
      bloodFlow: 5.5,
      temperature: 37.2,
      adrenaline: 125,
      heartRate: 74,
      spO2: 97,
      respiratoryRate: 16,
      hrv: 63,
      systolic: 123,
      diastolic: 81,
      stressLevel: 3,
    },
    location: {
      lat: 25.7617,
      lng: -80.1918,
      formatted: "Miami, FL",
    },
    imageUrl: "/placeholder.svg?height=200&width=200",
  },
]

export const bases: Base[] = [
  {
    id: "B-001",
    name: "Alpha Base",
    location: {
      lat: 32.7555,
      lng: -97.3308,
      formatted: "Fort Worth, TX",
    },
    soldiers: 150,
  },
  // Add more bases here...
]

export const events: Event[] = [
  {
    id: "E-001",
    type: "INFO",
    description: "System login successful - Admin user",
    timestamp: new Date().toISOString(),
  },
  // Add more events here...
]

